AppBundle\Entity\Offer:
    type: mappedSuperclass
    repositoryClass: AppBundle\Repository\OfferRepository
    id:
        uid:
            type: integer
            generator: { strategy: AUTO }
    lifecycleCallbacks: {}